name: Compile LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compile-tex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile all .tex files
      run: |
        mkdir -p compiled_pdfs
        find . -name '*.tex' | while read texfile; do
          dir=$(dirname "$texfile")
          base=$(basename "$texfile" .tex)
          pdffile="${base}.pdf"
          echo "Compiling $texfile"
          latexmk -pdf -interaction=nonstopmode -output-directory="$dir" "$texfile"
          if [ -f "$dir/$pdffile" ]; then
            cp "$dir/$pdffile" compiled_pdfs/
          fi
        done

    - name: Commit and push compiled PDFs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch
        git checkout main
        mkdir -p compiled_pdfs
        git add compiled_pdfs/*.pdf || echo "No PDFs to add"
        git commit -m "Add compiled PDFs" || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
